

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "1q2w3e4r@#$" # Senha do SQL Server
      ACCEPT_EULA: "Y" # Aceitar o contrato de licença
    ports:
      - "1433:1433" # Expõe a porta 1433 do SQL Server
    volumes:
      - sqlserverdata:/var/opt/mssql # Persistência dos dados do SQL Server

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Expõe a API na porta 8080
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=hundfit;User ID=sa;Password=1q2w3e4r@#$;Trusted_Connection=False;TrustServerCertificate=True;
    depends_on:
      - sqlserver # Garante que o SQL Server seja iniciado antes da API

volumes:
  sqlserverdata: